version: '3.8'
services:

  backend-mysql:
    image: mysql:8.0
    volumes:
      - ./.db_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"

  # backend-app:
  #   build: .
  #   ports:
  #     - "5000:5000" 
  #   volumes:
  #     - .:/app

  #   depends_on:
  #     - backend-mysql

